blank_issues_enabled: true
contact_links:
  - name: bitpulsed Core Security Policy
    url: https://github.com/bitcoin/bitcoin/blob/master/SECURITY.md
    about: View security policy
  - name: bitpulsed Core Developers
    url: https://bitcoincore.org
    about: bitpulsed Core homepage
